# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-0Y2RE5P41G'

menu:
- {name: 'Home',   url: ''}
- {name: 'Publications', url: 'publications.html'}
#- {name: 'Writing', url: 'writing.html'}
- {name: 'CV', url: 'assets/pdf/CV.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/francescodisalvo05'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/francescodisalvo-pa/'}
- {icon: 'twitter',    link: 'https://twitter.com/francescodis_'}
- {icon: 'envelope',   link: 'mailto:francesco.di-salvo@uni-bamberg.de'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
